[tool.coverage.run]
branch = true
source = [ "booking_users" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:'../../../coverage/packages/services/users/html' --cov-report xml:'../../../coverage/packages/services/users/coverage.xml' --html='../../../reports/packages/services/users/unittests/html/index.html' --junitxml='../../../reports/packages/services/users/unittests/junit.xml'"

[tool.poetry]
name = "booking-users"
version = "1.0.0"
description = "User management service"
authors = [ ]
license = "Proprietary"
readme = "README.md"

  [[tool.poetry.packages]]
  include = "booking_users"

  [tool.poetry.dependencies]
  python = ">=3.11,<3.13"
  uvicorn = "^0.34.0"
  httpx = "^0.28.1"
  python-multipart = "^0.0.20"
  asyncpg = "^0.30.0"
  psycopg2-binary = "^2.9.10"

    [tool.poetry.dependencies.booking-auth]
    path = "../../libs/auth"
    develop = true

    [tool.poetry.dependencies.booking-db]
    path = "../../libs/db"
    develop = true

    [tool.poetry.dependencies.booking-common]
    path = "../../libs/common"
    develop = true

    [tool.poetry.dependencies.booking-api]
    path = "../../libs/api"
    develop = true

    [tool.poetry.dependencies.booking-shared-models]
    path = "../../libs/shared-models"
    develop = true

[tool.poetry.group.dev.dependencies]
autopep8 = "2.3.1"
flake8 = "7.1.1"
pytest = "8.3.4"
pytest-sugar = "1.0.0"
pytest-cov = "6.0.0"
pytest-html = "4.1.1"
isort = "^6.0.1"
black = "^25.1.0"
pytest-asyncio = "^0.25.3"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
